import { NextResponse } from 'next/server';
import { createClient, SupabaseClient } from '@supabase/supabase-js';
import { queryKnowledgeBase } from '@/lib/gemini';
import { alertKnowledgeGap, alertPaymentVerification, alertRegistration } from '@/lib/notifications';
import { whatsappService } from '@/lib/whatsapp-service';
import { db } from '@/lib/db';
import { sendWhatsAppMessageDynamic } from '@/lib/whatsapp-sender';

export const dynamic = 'force-dynamic';

// Initialize Supabase Client with Service Key to bypass RLS policies
let cachedSupabase: SupabaseClient | null = null;

function getSupabaseClient() {
  if (!cachedSupabase) {
    const supabaseUrl = process.env.SUPABASE_URL || process.env.NEXT_PUBLIC_SUPABASE_URL || '';
    const supabaseServiceKey = process.env.SUPABASE_SERVICE_KEY || '';
    if (!supabaseUrl || !supabaseServiceKey) {
      console.warn('[webhook/whatsapp] Warning: Supabase URL or Service Key is missing. Webhook database operations might fail.');
    }
    // Explicitly configure connection to accept and send UTF-8 for utf8mb4 emoji support
    cachedSupabase = createClient(supabaseUrl, supabaseServiceKey, {
      auth: {
        persistSession: false
      },
      global: {
        headers: {
          'Content-Type': 'application/json; charset=utf-8',
          'Accept-Charset': 'utf-8'
        }
      }
    });
  }
  return cachedSupabase;
}

/**
 * GET /api/webhook/whatsapp
 * Meta Webhook verification endpoint
 */
export async function GET(request: Request) {
  const { searchParams } = new URL(request.url);
  const mode = searchParams.get('hub.mode');
  const token = searchParams.get('hub.verify_token');
  const challenge = searchParams.get('hub.challenge');

  if (mode === 'subscribe' && token) {
    const verifyToken = await db.getSystemSetting('whatsapp_verify_token') || 'fuxion_verify_token';
    if (token === verifyToken) {
      console.log('[webhook/whatsapp] Meta Webhook verified successfully!');
      return new Response(challenge, { status: 200 });
    } else {
      console.warn('[webhook/whatsapp] Meta Webhook verification failed. Tokens mismatch.');
      return new Response('Forbidden', { status: 403 });
    }
  }
  return new Response('Not Found', { status: 404 });
}

/**
 * Extracts phone digits from a WhatsApp ID.
 */
function getPhoneFromWhatsappId(id: string): string | null {
  if (!id || typeof id !== 'string') return null;
  const raw = id.split('@')[0] || '';
  let digits = raw.replace(/\D/g, '');
  if (digits.length === 9 && digits.startsWith('9')) {
    digits = '51' + digits;
  }
  return digits.length > 0 ? digits : null;
}

/**
 * Extracts the message text from different Evolution API / Baileys message payload structures.
 */
function extractMessageText(message: any): string | null {
  if (!message || typeof message !== 'object') return null;
  if (typeof message === 'string') return message;

  const messageTypes = [
    'conversation',
    'extendedTextMessage',
    'imageMessage',
    'videoMessage',
    'documentMessage',
    'audioMessage',
    'stickerMessage',
    'buttonsResponseMessage',
    'templateButtonReplyMessage',
    'listResponseMessage',
    'reactionMessage'
  ];

  for (const type of messageTypes) {
    if (message[type]) {
      const payload = message[type];
      if (type === 'conversation') return payload;
      if (type === 'extendedTextMessage') return payload?.text || payload?.contextInfo?.quotedMessage?.conversation || null;
      if (type === 'imageMessage' || type === 'videoMessage' || type === 'documentMessage' || type === 'audioMessage') {
        if (payload?.caption) return payload.caption;
        if (type === 'imageMessage') return '[Foto]';
        if (type === 'documentMessage') return '[Documento]';
        if (type === 'videoMessage') return '[Video]';
        if (type === 'audioMessage') return '[Audio]';
        return null;
      }
      if (type === 'stickerMessage') return payload?.url ? 'Sticker' : null;
      if (type === 'buttonsResponseMessage') return payload?.selectedButtonId || payload?.selectedDisplayText || null;
      if (type === 'templateButtonReplyMessage') return payload?.selectedId || payload?.selectedDisplayText || null;
      if (type === 'listResponseMessage') return payload?.singleSelectReply?.selectedRowId || payload?.singleSelectReply?.title || null;
      if (type === 'reactionMessage') return payload?.text || null;
    }
  }

  if (message.text) return message.text;
  if (message.textMessage?.text) return message.textMessage.text;

  return null;
}

/**
 * Detects if the user has an active conversation controlled by the IA.
 * If the last bot/agent message does not match any static flow node text,
 * then it was generated by the IA, meaning the IA has control.
 */
function hasActiveIAConversation(messages: any[], activeFlows: any[]): boolean {
  if (!messages || messages.length === 0) return false;

  const botMessages = messages.filter((m: any) => m.sender === 'bot');
  if (botMessages.length === 0) return false;

  const lastBotMsg = botMessages[botMessages.length - 1];
  const lastBotText = lastBotMsg.message || '';

  for (const flow of activeFlows) {
    for (const node of flow.nodes || []) {
      if (node.type === 'message' && node.data?.message) {
        if (lastBotText.includes(node.data.message)) {
          return false;
        }
      }
      if (node.type === 'buttons') {
        const btnText = (node.data?.buttons || []).map((b: string, i: number) => `👉 *${i+1}.* ${b}`).join('\n');
        if (lastBotText.includes(btnText)) {
          return false;
        }
      }
    }
  }

  return true;
}

/**
 * Sends a text message back to WhatsApp. 
 * Prioritizes Evolution API if configured, otherwise falls back to local Baileys service.
 */
async function sendWhatsAppMessage(phone: string, text: string) {
  await sendWhatsAppMessageDynamic(phone, text);
}



/**
 * POST handler to process Evolution API / Baileys events
 */
export async function POST(request: Request) {
  console.log('[webhook/whatsapp] POST called');

  // Si la sesión de Baileys local está activa en la base de datos, ignoramos el webhook externo.
  // Baileys procesa directamente los mensajes en tiempo real vía websocket en whatsapp-service.ts.
  try {
    const session = await db.getWhatsappSession('default');
    if (session && session.creds && session.creds.me && session.creds.me.id && !session.creds.me.id.startsWith('placeholder')) {
      const activeLocalPhone = getPhoneFromWhatsappId(session.creds.me.id) || '';
      console.log(`[webhook/whatsapp] Conexión local de Baileys activa (${activeLocalPhone}). Ignorando webhook externo.`);
      return NextResponse.json({ success: true, message: 'Ignored: Local Baileys session is active' });
    }
  } catch (e) {
    console.error('[webhook/whatsapp] Error al comprobar la sesión persistida:', e);
  }

  const supabase = getSupabaseClient();
  try {
    const body = await request.json();

    // Evolution API payload uses 'event' and 'data' keys
    const event = body.event;
    const data = body.data;

    // Check key and message structure
    const key = data?.key || body.key;
    const messageObj = data?.message || body.message;

    if (!key || !messageObj) {
      console.log('[webhook/whatsapp] Ignored: Not a valid message payload (missing key or message content)');
      return NextResponse.json({ success: true, message: 'Ignored: Missing key or message content' });
    }

    const fromMe = key.fromMe ?? false;

    // Resolve clean phone number from conversation JID (remoteJid represents the customer chat thread, prioritizing remoteJidAlt)
    const remoteJid = data?.key?.remoteJidAlt || key?.remoteJidAlt || data?.key?.remoteJid || key?.remoteJid || '';
    const hasAlt = !!(data?.key?.remoteJidAlt || key?.remoteJidAlt);
    const phoneJid = hasAlt ? (data?.key?.remoteJidAlt || key?.remoteJidAlt).toString() : remoteJid.toString();
    const lidJid = hasAlt ? (data?.key?.remoteJid || key?.remoteJid).toString() : null;

    let phone = getPhoneFromWhatsappId(phoneJid);
    let lid = lidJid ? getPhoneFromWhatsappId(lidJid) : null;

    // Si no se puede extraer de remoteJid, intentamos de sender
    if (!phone) {
      const senderJid = data?.sender || body?.sender || '';
      phone = getPhoneFromWhatsappId(senderJid);
    }

    // Normalización Universal de JID tipo LID
    if (phoneJid.endsWith('@lid') && phone) {
      const normalizedPhoneJid = await db.normalizeJid(phoneJid);
      if (normalizedPhoneJid !== phoneJid) {
        lid = phone;
        phone = getPhoneFromWhatsappId(normalizedPhoneJid);
      }
    }

    // Tabla de Mapeo de Identidad estática para celular vinculado
    if (phone && db.IDENTITY_MAPPING[phone]) {
      const staticEquivs = db.IDENTITY_MAPPING[phone];
      const realPhone = staticEquivs.find((id: string) => id !== phone && id.startsWith('51'));
      if (realPhone) {
        console.log(`[webhook/whatsapp] Normalizando ID ${phone} a número real mapeado estáticamente: ${realPhone}`);
        if (!lid) lid = phone;
        phone = realPhone;
      }
    }

    // Si por alguna razón el remitente no se puede leer, arroja un console.error con el objeto completo
    if (!phone) {
      console.error('[webhook/whatsapp] ERROR: No se pudo leer el remitente del mensaje. Objeto completo:', JSON.stringify(body, null, 2));
      return NextResponse.json({ success: false, error: 'Remitente no legible' }, { status: 400 });
    }

    // Ignorar número de prueba de Meta/Sandbox para que no ensucie la base de datos
    if (phone === '141532090908916' || phone.startsWith('1415')) {
      console.log('[webhook/whatsapp] Ignorando número de prueba de Meta/Sandbox:', phone);
      return NextResponse.json({ success: true, message: 'Ignored test number' });
    }

    // Ignore group chats, status, or empty phone
    if (remoteJid === 'status@broadcast' || remoteJid.endsWith('@broadcast') || remoteJid.endsWith('@g.us')) {
      console.log('[webhook/whatsapp] Ignored: Group, broadcast or status message');
      return NextResponse.json({ success: true, message: 'Ignored: Group or broadcast message' });
    }

    // Extract text directly. No cleaning, stripping, or sanitization is done to the message content,
    // ensuring complete support for special characters and complex utf8mb4 emojis (e.g. 🥺).
    const rawMessageText = extractMessageText(messageObj);
    if (!rawMessageText) {
      console.log('[webhook/whatsapp] Ignored: No text extractable from message');
      return NextResponse.json({ success: true, message: 'Ignored: Empty message body' });
    }
    let messageText: string = rawMessageText;

    const leadId = phone;
    const pushName = data?.pushName || body.pushName || `WhatsApp ${phone}`;
    const cleanName = pushName.trim();

    // If message is outgoing (sent by us or from physical phone of agent)
    if (fromMe) {
      console.log(`[webhook/whatsapp] Logging outgoing message: direction = 'outgoing', sender = 'agent', source = 'mobile_device' for lead ${leadId}`);

      // Check if this outgoing message is a duplicate of a recent bot message to avoid double-logging
      const recentMessages = await db.getMessages(leadId);
      const isBotDuplicate = recentMessages.slice(-3).some(
        (m: any) => m.sender === 'bot' && m.message.trim() === messageText.trim()
      );

      if (isBotDuplicate) {
        console.log(`[webhook/whatsapp] Outgoing message is a duplicate of a recent bot response. Skipping agent log.`);
        return NextResponse.json({ success: true, message: 'Ignored: Bot loopback message' });
      }

      // Check if this outgoing message is a duplicate of a recent agent message sent within the last 5 seconds
      const nowMs = Date.now();
      const isAgentDuplicate = recentMessages.some((m: any) => {
        if (m.sender !== 'agent' || m.message !== messageText) {
          return false;
        }

        let isoStr = m.created_at;
        if (typeof isoStr === 'string') {
          if (!isoStr.includes('T')) {
            isoStr = isoStr.replace(' ', 'T');
          }
          if (!isoStr.endsWith('Z') && !isoStr.match(/[+-]\d{2}:?\d{2}$/)) {
            isoStr += 'Z';
          }
        }
        const msgTime = new Date(isoStr).getTime();
        const diffSeconds = (nowMs - msgTime) / 1000;
        return diffSeconds >= 0 && diffSeconds <= 5;
      });

      if (isAgentDuplicate) {
        console.log(`[webhook/whatsapp] Outgoing message is a duplicate of a recent agent message sent within 5 seconds. Ignoring.`);
        return NextResponse.json({ success: true, message: 'Ignored: Agent duplicate message within 5s' });
      }

      // Ensure lead exists
      await db.upsertLead({
        id: leadId,
        name: cleanName,
        phone: phone,
        whatsapp_lid: lid,
        status: 'New',
        tags: [],
        bot_active: true
      });

      // Save outgoing message (uses WhatsApp key ID to avoid duplicates)
      const msgId = key.id || `msg-${Date.now()}-${Math.random().toString(36).substring(2, 11)}`;
      if (process.env.SUPABASE_URL && process.env.SUPABASE_ANON_KEY) {
        await supabase.from('chat_messages').upsert({
          id: msgId,
          lead_id: leadId,
          sender: 'agent',
          message: messageText
        }, { onConflict: 'id' });
      } else {
        await db.addMessage(leadId, 'agent', messageText, msgId);
      }

      return NextResponse.json({ success: true, message: 'Logged outgoing message' });
    }

    // --- Incoming Message Processing (from client) ---
    console.log(`[webhook/whatsapp] Processing incoming message from customer: ${phone}, text: "${messageText}"`);

    // 1. Fetch or create lead using database helper
    let activeLead = await db.getLeadById(leadId);
    if (!activeLead) {
      activeLead = await db.upsertLead({
        id: leadId,
        name: cleanName,
        phone: phone,
        whatsapp_lid: lid,
        status: 'New',
        tags: [],
        bot_active: true
      });
    } else if (lid && activeLead.whatsapp_lid !== lid) {
      // Si el LID cambió o se detectó por primera vez, lo actualizamos
      activeLead = await db.upsertLead({
        id: leadId,
        name: activeLead.name || cleanName,
        phone: activeLead.phone || phone,
        whatsapp_lid: lid
      });
    }

    // 2. Save incoming message to database
    const msgId = key.id || `msg-${Date.now()}-${Math.random().toString(36).substring(2, 11)}`;
    if (process.env.SUPABASE_URL && process.env.SUPABASE_ANON_KEY) {
      await supabase.from('chat_messages').upsert({
        id: msgId,
        lead_id: leadId,
        sender: 'customer',
        message: messageText
      }, { onConflict: 'id' });
    } else {
      await db.addMessage(leadId, 'customer', messageText);
    }

    // Detectar si el cliente envió un comprobante (imagen/foto) después de recibir datos de pago
    const isPaymentAttachment = messageObj.imageMessage || messageText === '[Foto]';
    if (isPaymentAttachment) {
      const recentMsgs = await db.getMessages(leadId);
      const hasSentPaymentDetails = recentMsgs.slice(-5).some(m => {
        if (m.sender !== 'bot' && m.sender !== 'agent') return false;
        const msgLower = m.message.toLowerCase();
        return msgLower.includes('955252932') || msgLower.includes('yape') || msgLower.includes('plin') || msgLower.includes('transferenci');
      });

      if (hasSentPaymentDetails) {
        console.log(`[webhook/whatsapp] 💳 Comprobante recibido para el lead ${leadId}. Actualizando a Verificación Pendiente y pausando bot.`);
        await db.updateLeadStatus(leadId, 'Pending Verification');
        await db.updateLeadBotActive(leadId, false);
        
        const autoReply = '¡Muchas gracias por tu pago! Tu comprobante ha sido recibido. Un asesor humano lo verificará en unos minutos y procederemos con tu entrega. ¡Que tengas un excelente día! 😊';
        await db.addMessage(leadId, 'bot', autoReply);
        await sendWhatsAppMessage(activeLead.phone || phone, autoReply);
        return NextResponse.json({ success: true, reply: autoReply });
      }
    }

    // Detectar si el mensaje es un disparador de un flujo activo para reactivar el bot
    let isBotActive = activeLead.bot_active === 1 || activeLead.bot_active === true;
    
    const flows = await db.getFlows();
    const activeFlows = flows.filter((f: any) => f.is_active);

    let messageTriggersFlow = false;
    for (const flow of activeFlows) {
      if (flow.nodes) {
        const triggerNode = flow.nodes.find((n: any) => n.type === 'trigger');
        if (triggerNode) {
          const keywords = (triggerNode.data.keyword || '').split(',').map((k: string) => k.trim().toLowerCase()).filter((k: string) => k.length > 0);
          const cleanText = messageText.toLowerCase().trim();
          const matches = keywords.some((k: string) => cleanText === k || (cleanText.length <= k.length + 3 && cleanText.includes(k)));
          if (matches) {
            messageTriggersFlow = true;
            break;
          }
        }
      }
    }

    if (messageTriggersFlow) {
      console.log(`[webhook/whatsapp] Mensaje coincide con disparador. Reactivando bot para ${leadId}.`);
      await db.updateLeadBotActive(activeLead.id, true);
      isBotActive = true;
      whatsappService.flowState.delete(leadId);
    }

    if (!isBotActive) {
      console.log(`[webhook/whatsapp] Bot is paused for lead ${leadId}. Message logged.`);
      return NextResponse.json({ success: true, message: 'Message logged. Bot is paused.' });
    }



    // 4. Retrieve recent message history for AI context
    const historyMessages = await db.getMessages(leadId);
    const history = historyMessages.slice(-10).map((m: any) => ({
      sender: m.sender,
      message: m.message
    }));

    // 3.5. Flow Priority System Check

    const hasIAControl = hasActiveIAConversation(historyMessages, activeFlows);
    const isWaitingClose = activeLead.status === 'Pending Verification';

    let isFlowTriggered = false;
    
    // Evaluar si una palabra clave del flujo fuerza el reinicio del flujo
    if (!hasIAControl && !isWaitingClose) {
      for (const flow of activeFlows) {
        const triggerNode = flow.nodes?.find((n: any) => n.type === 'trigger');
        if (triggerNode) {
          const keywords = (triggerNode.data?.keyword || '').split(',').map((k: string) => k.trim().toLowerCase()).filter((k: string) => k.length > 0);
          if (keywords.some((k: string) => messageText.toLowerCase().includes(k))) {
            isFlowTriggered = true;
            break;
          }
        }
      }
    }

    const inFlowState = whatsappService.flowState?.has(leadId);

    // CONTROL CRÍTICO: Si la IA ya tomó el control de la conversación, 
    // se ignora el estado del flujo activo para evitar reinicios forzados del menú.
    if (!hasIAControl && (isFlowTriggered || inFlowState)) {
      console.log(`[webhook/whatsapp] Flow triggered or active flow state detected for lead ${leadId}. Executing flow...`);
      const flowContext = { overrideText: null as string | null };
      const flowReply = await whatsappService.executeActiveFlow(
        leadId,
        messageText,
        activeLead.phone || phone,
        flowContext,
        async (p: string, t: string) => {
          await sendWhatsAppMessage(p, t);
        }
      );

      if (flowReply) {
        await db.addMessage(leadId, 'bot', flowReply);
        console.log(`[webhook/whatsapp] Flow response sent: "${flowReply}"`);
        return NextResponse.json({ success: true, reply: flowReply });
      } else if (flowContext.overrideText) {
        console.log(`[webhook/whatsapp] Flow set override text to: "${flowContext.overrideText}". Querying Gemini...`);
        messageText = flowContext.overrideText;
      }
    } else if (hasIAControl) {
      console.log(`[webhook/whatsapp] 🧠 IA activa detectada para el lead ${leadId}. Omitiendo flujos automáticos.`);
    }

    // 3.1 Stop if AI is globally disabled by the operator
    const aiGloballyEnabled = typeof globalThis.AI_GLOBALLY_ENABLED === 'undefined' ? true : globalThis.AI_GLOBALLY_ENABLED;
    if (!aiGloballyEnabled) {
      console.log(`[webhook/whatsapp] AI is globally disabled. Message logged for lead ${leadId}, no AI response sent.`);
      return NextResponse.json({ success: true, message: 'Message logged. AI globally disabled.' });
    }

    // 5. Query Gemini AI with RAG Context
    const reply = await queryKnowledgeBase(messageText, history);
    console.log(`[webhook/whatsapp] AI Response: "${reply}"`);

    // 6. Handle UNKNOWN replies (Shadow Mode Activation)
    if (reply.trim() === '[UNKNOWN]') {
      console.log(`[webhook/whatsapp] AI could not answer. Pausing bot and creating knowledge gap task.`);

      // Pause bot
      await db.updateLeadBotActive(activeLead.id, false);

      // Determine appropriate status update
      let newStatus = activeLead.status || 'New';
      const lowerText = messageText.toLowerCase();
      if (lowerText.includes('pay') || lowerText.includes('comprar') || lowerText.includes('pago')) {
        newStatus = 'Pending Verification';
      } else {
        newStatus = 'Engaged';
      }

      await db.updateLeadStatus(activeLead.id, newStatus);

      // Construct history snippet for knowledge gap context
      const contextSnippet = history
        .slice(-4)
        .map((m: any) => `${m.sender}: ${m.message}`)
        .join('\n');

      const gapId = `gap-${Date.now()}-${Math.random().toString(36).substring(2, 7)}`;
      await db.addGap(gapId, activeLead.id, messageText, contextSnippet);

      // Send email alert for Knowledge Gap
      await alertKnowledgeGap({
        name: activeLead.name || cleanName,
        phone: activeLead.phone || phone
      }, messageText);

      // Save fallback bot message
      const fallbackReply = 'Lo siento, no tengo esa información en este momento. Un agente humano revisará su pregunta y le responderá a la brevedad.';
      await db.addMessage(leadId, 'bot', fallbackReply);

      // Reply back via WhatsApp
      await sendWhatsAppMessage(activeLead.phone || phone, fallbackReply);

      return NextResponse.json({
        success: true,
        reply: fallbackReply,
        bot_active: false,
        gapCreated: true
      });
    }

    // 7. Detect [REGISTRO_DETECTADO] tag from AI response
    const registroMatch = reply.match(/\[REGISTRO_DETECTADO:([^|\]]+)\|([^|\]]+)\|([^|\]]+)\|([^\]]+)\]/);
    if (registroMatch) {
      const [, regNombre, regDni, regCelular, regCorreo] = registroMatch;
      // Strip the internal tag from the visible message
      const confirmMsg = reply.replace(/\[REGISTRO_DETECTADO:[^\]]+\]/, '').trim();
      // The follow-up payment question is embedded or we add it separately
      const paymentFollowUp = 'Mientras procesamos tu registro y te llamamos, ¿cómo te gustaría dejar programado el pago de tu pedido de hoy? ¿Por Yape o transferencia?';

      // Save and send the confirmation message
      await db.addMessage(leadId, 'bot', confirmMsg);
      await sendWhatsAppMessage(activeLead.phone || phone, confirmMsg);

      // Wait a moment then send the payment question as a second message
      await new Promise(r => setTimeout(r, 1200));
      await db.addMessage(leadId, 'bot', paymentFollowUp);
      await sendWhatsAppMessage(activeLead.phone || phone, paymentFollowUp);

      // Pause bot and update lead status to Por Registrar en Web
      await db.updateLeadBotActive(activeLead.id, false);
      await db.updateLeadStatus(activeLead.id, 'Por Registrar en Web');

      // Determine CRM base URL dynamically from request.url
      let crmBase = 'http://localhost:3000';
      try {
        const reqUrl = new URL(request.url);
        crmBase = reqUrl.origin;
      } catch (e) {
        crmBase = process.env.NEXT_PUBLIC_APP_URL || 'http://localhost:3000';
      }

      // Fire admin WhatsApp alert with client data
      await alertRegistration({
        nombre: regNombre.trim(),
        dni: regDni.trim(),
        celular: regCelular.trim(),
        correo: regCorreo.trim(),
        leadId: activeLead.id,
        crmBaseUrl: crmBase
      });

      console.log(`[webhook/whatsapp] 🎯 Registro detectado para lead ${leadId}. Bot pausado. Alerta al admin disparada.`);
      return NextResponse.json({ success: true, reply: confirmMsg, registroDetectado: true });
    }

    // 7. Save Bot Response to Logs
    await db.addMessage(leadId, 'bot', reply);

    // 8. Reply back via WhatsApp
    await sendWhatsAppMessage(activeLead.phone || phone, reply);

    // 9. Payment verification keywords trigger
    const paymentKeywords = ['yape', 'plin', 'transferencia', 'banco', 'pago', 'recibo', 'comprobante', 'voucher', 'pagar'];
    const isPaymentTrigger = paymentKeywords.some(keyword => messageText.toLowerCase().includes(keyword));

    if (isPaymentTrigger && activeLead.status !== 'Pending Verification') {
      await db.updateLeadStatus(activeLead.id, 'Pending Verification');

      let currentTags: string[] = [];
      try {
        currentTags = typeof activeLead.tags === 'string' ? JSON.parse(activeLead.tags) : (activeLead.tags || []);
      } catch (e) {
        currentTags = [];
      }

      if (!currentTags.includes('needs-verification')) {
        currentTags.push('needs-verification');
        await db.updateLeadTags(activeLead.id, currentTags);
      }

      await alertPaymentVerification({
        name: activeLead.name || cleanName,
        phone: activeLead.phone || phone,
        status: 'Pending Verification'
      });
    }

    return NextResponse.json({ success: true, reply });

  } catch (error: any) {
    console.error('[webhook/whatsapp] Error handling webhook:', error);
    return NextResponse.json({ error: error.message || 'Internal Server Error' }, { status: 500 });
  }
}
